[package]
name = "television-utils"
version = "0.0.0"
edition = "2021"

[dependencies]
ignore = "0.4.23"
infer = "0.16.0"
lazy_static = "1.5.0"
tracing = "0.1.40"
color-eyre = "0.6.3"
bat = "0.24.0"
directories = "5.0.1"
syntect = "5.2.0"