[keybindings.Input]
q = "Quit"
esc = "Quit"
ctrl-c = "Quit"
ctrl-z = "Suspend"
tab = "GoToNextPane"
backtab = "GoToPrevPane"
ctrl-left = "GoToPaneLeft"
ctrl-right = "GoToPaneRight"
down = "SelectNextEntry"
up = "SelectPrevEntry"
ctrl-n = "SelectNextEntry"
ctrl-p = "SelectPrevEntry"
ctrl-down = "ScrollPreviewDown"
ctrl-up = "ScrollPreviewUp"
ctrl-d = "ScrollPreviewHalfPageDown"
ctrl-u = "ScrollPreviewHalfPageUp"
enter = "SelectEntry"
